[package]
name = "vbus-examples"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vbus-core = { path =  "../vbus-core" }
vbus-sensors = { path =  "../vbus-sensors" }
